name: Github pages

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.83.1'
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install npm packages
        working-directory: ./site
        run: |
          npm ci

      - name: Install Poetry Action
        uses: snok/install-poetry@v1.3.2

      # click>=8.1.0 fails https://github.com/streamlit/streamlit/issues/4555
      - name: Build docs
        run: |
          poetry install --with docs,dev --all-extras
          sphinx-versioning -l site/source/conf.py build -r develop -w develop site/source site/static/api
          python site/build_docs.py

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
