name: Build
on:
  workflow_dispatch: # for testing
  pull_request:
    branches:
      - 'master'
      - 'releases/*'
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  push:
    branches:
      - 'develop'

# This is what will cancel the workflow concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check_integrity:
    strategy:
      fail-fast: false
      matrix:
        os: ['macos-14', 'ubuntu-24.04', 'windows-2022']
        include:
          - python-version: "3.10"
            tox-env-py: "310"
          - python-version: "3.11"
            tox-env-py: "311"
          - python-version: "3.12"
            tox-env-py: "312"
          - os: "ubuntu-24.04"
            tox-env-os: "lin"
          - os: "windows-2022"
            tox-env-os: "win"
          - os: "macos-14"
            tox-env-os: "mac"
    name: health check (${{ matrix.os }}, Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Installing Rust toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7, locked for security
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Installing python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Installing dependencies
        run: |
          python -m pip install tox
      - name: Rust unit tests
        run: |
          cd rust/
          cargo test
      - name: Code instrumentation
        run: |
          tox -e tests-py${{ matrix.tox-env-py }}-lin
