name: Regular healthcheck

on:
  schedule:
    # every UTC 6PM at Mon, Wed, Fri
    - cron: "0,10,20,30,40,50 * * * *"

# This is what will cancel the workflow concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check_integrity:
    steps:
      - name: Test
        run: |
          echo "test"
